import type { Metadata } from "next";
import "./globals.css";
import SiteAnimations from "@/src/hooks/site-animations";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="id"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col font-sans">
        <SiteAnimations />
        {children}
      </body>
    </html>
  );
}
