CREATE TABLE IF NOT EXISTS social_links (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    label VARCHAR(100) NOT NULL,

    url VARCHAR(500) NOT NULL,

    icon VARCHAR(150),

    sort_order INT NOT NULL DEFAULT 0,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_social_links_sort_order (sort_order)

)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;