CREATE TABLE IF NOT EXISTS jam_operasional (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    day_label VARCHAR(100) NOT NULL,

    open_time TIME DEFAULT NULL,

    close_time TIME DEFAULT NULL,

    is_24_hours BOOLEAN NOT NULL DEFAULT FALSE,

    note VARCHAR(255) DEFAULT NULL,

    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_jam_operasional_sort_order (sort_order)

)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;